### ISSUE TITLE
SelectLocationVC 건물 선택 화면 구현

### ISSUE THREAD

**Issue by minsangKang** [FreeDeveloper97/point-cloud-with-lidar#11]
### 요구사항 ID
- [SFR-017](https://github.com/FreeDeveloper97/point-cloud-with-lidar/wiki/Requirements#sfr-017)
- [UFR-APP-003](https://github.com/FreeDeveloper97/point-cloud-with-lidar/wiki/Requirements#ufr-app-003)
- [UI-A-005](https://github.com/FreeDeveloper97/point-cloud-with-lidar/wiki/Interfaces#ui-a-005)

### 기능 명세
- 뷰어(iOS 앱 및 웹 브라우저)에서 주소 검색 API 와 연계하여 위치정보(GPS 등) 근처 건물 정보를 조회하는 기능
- LiDAR 측정종료 후 2D 지도상에서 사용자의 위치 확인 및 측정위치를 선택 후 표시된 건물리스트 중 측정건물 선택
- SelectLocationVC 건물 선택 화면

### 우선순위
M

### 요구사항
- [x] VM: mode 값
- [x] VM: changeMode() 구현
- [x] BuildingNearByGpsDTO 생성
- [x] BuildingInfo 생성
- [x] BuildingApiService 생성
- [x] BuildingRepositoryInterface 생성
- [x] BuildingRepository 생성
- [x] VM: page 값
- [x] VM: buildingList 값
- [x] fetchBuildingList() 구현
- [x] nextPageBuildingListFetch() 구현
- [x] buildingListView 생성
- [x] bindMode() 구현
- [x] bindBuildingList() 구현
- [x] backButton 생성

**Comment by jeonwookyun** [comment]
보통 태스크 설계를 할 때는 최대한 작게 설계를 하는게 좋습니다. 이 티켓을 보면 화면을 기준으로 Task 티켓이 설계가 되어 있는데요.
일단 이 티켓은 범위가 너무 큰것으로 보입니다. 보통 Task 티켓을 설계할 때는 워킹데이 4일을 넘지 않도록 하는게 일반적이에요.
티켓이 너무 크면 In Progress 상태로 너무 오래 남게 되고 이렇게되면 이티켓이 어떻게 진행되고 있는지 파악하는게 어려워집니다. 
내부적으로 Checkbox 로 세부 테스크를 관리하는걸로 보이지만 이렇게 되면 사실 전체 진행을 파악하기가 힘들어요.

프로젝트를 진행할 때 Epic -> Story -> Task -> Sub-task 로 티켓을 관리를 하는데요.
- Epic: 도메인 정도의 규모를 나타낼 수 있는 단위 (회원, 구매)
- Story: 사용자 스토리 정도의 단위인데 예를 들면 이렇습니다 
  ex) 회원 가입 페이지에서 사용자는 회원 가입을 할 수 있다
- Task: Story 를 구현하기 위해 진행해야하는 세부 목록 입니다.  (4일을 넘지 않도록 세분화 합니다)
  ex1) 회원 가입 화면 구현
  ex2) 회원 가입 API 연동
  ex3) 회원가입 유효성 체크로직 구현
- Sub-task: Task에서 별도의 하위 태스크로 관리되어야 하는 경우 Sub-task 로 관리합니다. (일반적으로는 Task로 정도면 충분합니다)
  ex) 위의 ex3 예에서 아이디를 입력하지 않으면 빨간색으로 표시가 되고 아래에 관련된 에러메세지를 노출한다.

아래는 Atlassian 에서 가이드하고 있는 내용인데요. 한번 읽어보시면 좋을 것 같아요.
https://www.atlassian.com/ko/agile/project-management/epics-stories-themes

**Comment by minsangKang** [comment]
@jeonwookyun Task가 좀 큰게 없잖아 있긴 하네요ㅠㅠ 오늘 하루안에 다 마무리할거긴해요! 한번 확인해볼께요 감사합니다!
